### ISSUE TITLE
Firefox port?

### ISSUE THREAD

**Issue by jay-ramani** [Lootyhoof/theme-tweaker#1]
Is there any chance this getting Firefox love? As of now, attempting to install on it says "... it appears to be corrupt". I've attached a screenshot showing the same.

Thanks and cheers.
![Corruption Error](https://user-images.githubusercontent.com/7327430/92280171-da340900-eec6-11ea-9a9b-b633621a3630.png)

**Comment by jay-ramani** [comment]
Update: I opened the browser console window (Ctrl+Shift+J) and found the error is because of an invalid manifest:

```16:02:05.837 1599249725836	addons.xpi	WARN	Invalid XPI: Error: File theme-tweaker-1-0-0-pm.xpi does not contain a valid manifest(resource://gre/modules/addons/XPIInstall.jsm:669:11) JS Stack trace: loadManifest@XPIInstall.jsm:669:11```

I did a bit of searching, but am clueless on the fix. Would you have any idea on how we can fix the manifest for Firefox?

Thanks much in advance. Cheers.

**Comment by Lootyhoof** [comment]
The add-on is for Pale Moon, not Firefox.

Incidentally, this is forked from Theme Font & Size Changer, a Firefox add-on. I'd recommend you use that.

**Comment by jay-ramani** [comment]
> 
> 
> The add-on is for Pale Moon, not Firefox.
> 
> Incidentally, this is forked from Theme Font & Size Changer, a Firefox add-on. I'd recommend you use that.

Yup, I'm aware of that. In fact, I used to use Theme Font & Size Changer, but is broken on Firefox now. It was last updated ~~in 2017~~ on 7th April 2020.

Thanks for the quick response though. I'll try to figure a way to have this working on Firefox.
